export const CREATE_TRANSACTION = '@financials/CREATE_TRANSACTION'
export const DELETE_TRANSACTION = '@financials/DELETE_TRANSACTION'
export const CLEAR_TRANSACTIONS = '@financials/CLEAR_TRANSACTIONS'
export const REMOVE_DELETED_USER = '@financials/REMOVE_DELETED_USER'
